[server]
    port = "8000"
    imagePath = "./images"
    host = "http://localhost:8000"

[postgres]
    user = "master_user"
    password = "master_password"
    host = "localhost"
    port = "5432"
    dbname = "picturesdb"
