[server]
    port = "8000"
    imagePath = "./images"
    host = "http://localhost:8000"

[postgres]
    user = "gorm"
    password = "gorm"
    host = "db"
    port = "5432"
    dbname = "pictures-db"
