version: "3"
services:
  db:
    image: postgres:11.6
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    tty: true

volumes:
  psql: